- name: Install Alertmanager (binary)
  ansible.builtin.unarchive:
    src: "https://github.com/prometheus/alertmanager/releases/download/v0.27.0/alertmanager-0.27.0.linux-amd64.tar.gz"
    dest: /opt/
    remote_src: yes
    creates: /opt/alertmanager-0.27.0.linux-amd64

- name: Symlink binaries
  ansible.builtin.file:
    src: "/opt/alertmanager-0.27.0.linux-amd64/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    state: link
  loop:
    - alertmanager
    - amtool

- name: Create config dir
  ansible.builtin.file:
    path: /etc/alertmanager
    state: directory
    mode: '0755'

- name: Template alertmanager.yml
  ansible.builtin.template:
    src: alertmanager.yml.j2
    dest: /etc/alertmanager/alertmanager.yml
    mode: '0644'
  notify: Restart alertmanager

- name: Install systemd unit
  ansible.builtin.copy:
    dest: /etc/systemd/system/alertmanager.service
    mode: '0644'
    content: |
      [Unit]
      Description=Prometheus Alertmanager
      After=network.target

      [Service]
      ExecStart=/usr/local/bin/alertmanager \
        --config.file=/etc/alertmanager/alertmanager.yml \
        --storage.path=/var/lib/alertmanager
      Restart=on-failure

      [Install]
      WantedBy=multi-user.target
  notify: Daemon-reload

- name: Ensure data dir
  ansible.builtin.file:
    path: /var/lib/alertmanager
    state: directory
    mode: '0755'

- name: Start & enable
  ansible.builtin.systemd:
    name: alertmanager
    state: started
    enabled: true

# Optional: ship starter alert rules for Prometheus to load
- name: Install starter node alert rules
  ansible.builtin.copy:
    src: files/node-alerts.yml
    dest: /etc/prometheus/rules/node-alerts.yml
    mode: '0644'
  notify: Restart prometheus
